if Code.ensure_loaded?(Ecto) do
  defmodule StatifierPersistence.Ecto do
    @moduledoc """
    Compile-time Ecto configuration on the host's own module (ADR-0002).

    A host declares its persistence module once:

        defmodule MyApp.Persistence do
          use StatifierPersistence.Ecto, repo: MyApp.Repo
        end

    and gets, with zero further options: the resolved configuration
    readable via `MyApp.Persistence.__statifier_persistence__/1`, and
    three Ecto schema modules - `MyApp.Persistence.Chart`,
    `MyApp.Persistence.Position`, `MyApp.Persistence.Run` - over the
    `statifier_charts` / `statifier_positions` / `statifier_runs` tables
    with UXID string primary keys (`chart_` / `pos_` / `run_` prefixes).

    Every knob is compile-time, on this `use`, never in application env
    (ADR-0002 decision 3), and the migrations helper consumes the same
    resolved configuration so schemas and DDL cannot disagree. See
    `StatifierPersistence.Ecto.Config` for the options (`:key`,
    `:table_prefix`, `:tables`, `:prefix`, `:blob_type`).

    The engine identity columns (`content_hash`, `session_id`, `run_id`)
    are stored verbatim as strings and are never touched by the
    configured key scheme - ADR-0002 decision 1.

    The runs schema also carries `metadata`, the optional opaque map of
    host identities ADR-0006 grants, as a `jsonb` column (V02 of the
    migrations helper). It holds identities only, never personal data:
    `:blob_type` does not reach it, so anything filed there is at rest in
    the clear no matter how the blob columns are configured.

    `:blob_type` reaches exactly three columns - `identity_blob`,
    `chart_blob`, `position_blob` - and nothing else: a host wanting
    encryption at rest for those payload columns passes a custom
    `Ecto.Type` or `Ecto.ParameterizedType` there and gets it applied
    with zero further wiring. The identity and lookup columns
    (`content_hash`, `session_id`, `run_id`, `status`, `failure`) stay
    plain text regardless - the identity guard and the unique indexes
    depend on reading them back verbatim, and `metadata` stays `jsonb`
    regardless for the same reason: it is the column a host queries
    (ADR-0006 decision 3).
    """

    alias StatifierPersistence.Ecto.Config

    @schema_modules [{Chart, :charts}, {Position, :positions}, {Run, :runs}]

    # The columns :blob_type reaches - identity/lookup columns never do
    # (moduledoc, Config's :blob_type option).
    @blob_columns [:identity_blob, :chart_blob, :position_blob]

    # The storage contract's field set is the column list (ADR-0003
    # decision 3); the migrations helper's V01 DDL mirrors these exactly.
    # Blob columns are typed :binary here; schema_ast/3 substitutes the
    # configured :blob_type for any column in @blob_columns.
    @fields %{
      charts: [content_hash: :string, identity_blob: :binary, chart_blob: :binary],
      positions: [
        session_id: :string,
        content_hash: :string,
        identity_blob: :binary,
        position_blob: :binary
      ],
      runs: [
        run_id: :string,
        status: :string,
        content_hash: :string,
        identity_blob: :binary,
        position_blob: :binary,
        failure: :string,
        session_id: :string,
        metadata: :map
      ]
    }

    defmacro __using__(opts) do
      quote bind_quoted: [opts: opts] do
        @statifier_persistence_config StatifierPersistence.Ecto.Config.new(opts)

        @doc false
        @spec __statifier_persistence__(:config | :repo) ::
                StatifierPersistence.Ecto.Config.t() | module()
        def __statifier_persistence__(:config), do: @statifier_persistence_config
        def __statifier_persistence__(:repo), do: @statifier_persistence_config.repo

        StatifierPersistence.Ecto.__define_schemas__(__MODULE__, @statifier_persistence_config)
      end
    end

    @doc false
    @spec __define_schemas__(module(), Config.t()) :: :ok
    def __define_schemas__(host, %Config{} = config) do
      for {name, table} <- @schema_modules do
        Module.create(
          Module.concat(host, name),
          schema_ast(host, table, config),
          Macro.Env.location(__ENV__)
        )
      end

      :ok
    end

    defp schema_ast(host, table, %Config{} = config) do
      fields =
        for {field, type} <- Map.fetch!(@fields, table) do
          args =
            if field in @blob_columns do
              Config.blob_field_args(config, field)
            else
              [field, type]
            end

          quote do: field(unquote_splicing(args))
        end

      quote do
        @moduledoc """
        Ecto schema for the `#{unquote(Config.table(config, table))}` table,
        generated by `use StatifierPersistence.Ecto` on
        `#{unquote(inspect(host))}`.
        """

        use Ecto.Schema

        @schema_prefix unquote(config.prefix)
        @primary_key unquote(Macro.escape(primary_key(table, config)))
        schema unquote(Config.table(config, table)) do
          unquote_splicing(fields)
          timestamps(type: :utc_datetime_usec)
        end
      end
    end

    defp primary_key(table, %Config{key: {key_mod, key_opts}}) do
      type = key_mod.ecto_type(key_opts)

      case key_mod.autogenerate(table, key_opts) do
        # Database-assigned (e.g. bigserial): read the key back on insert.
        nil -> {:id, type, autogenerate: false, read_after_writes: true}
        {_m, _f, _a} = mfa -> {:id, type, autogenerate: mfa}
      end
    end
  end
end
