defmodule StatifierPersistence.Ecto.KeyGenerator.UXID do
  @moduledoc """
  The default key generator: k-sortable UXID strings (ADR-0002 decision 2).

  Keys are generated by the `uxid` package and carry per-table prefixes in
  the engine's own style - `chart_`, `pos_`, `run_` (ADR-0002 decision 4,
  as amended) - so a key met in a psql console or a log line names its
  table. Stored as `:string` fields over `:text` columns.

  Options given to the generator (via `{module, opts}` or the resolved
  default) are passed through to `UXID.generate!/1`; the per-table
  `:prefix` is supplied unless the options already carry one.
  """

  @behaviour StatifierPersistence.Ecto.KeyGenerator

  # UXID's default delimiter is "_", so a "chart" prefix yields "chart_...".
  @prefixes %{charts: "chart", positions: "pos", runs: "run"}

  @impl true
  def ecto_type(_opts), do: :string

  @impl true
  def migration_type(_opts), do: :text

  @impl true
  def autogenerate(table, opts) do
    # UXID here is the uxid package's module, not this one - a flat
    # defmodule creates no alias for its last segment.
    {UXID, :generate!, [Keyword.put_new(opts, :prefix, Map.fetch!(@prefixes, table))]}
  end
end
