defmodule StatifierPersistence.EctoTest do
  use ExUnit.Case, async: true

  alias StatifierPersistence.Ecto.Config
  alias StatifierPersistence.Ecto.KeyGenerator
  alias StatifierPersistence.EctoHosts.Bigserial
  alias StatifierPersistence.EctoHosts.BlobTyped
  alias StatifierPersistence.EctoHosts.Default
  alias StatifierPersistence.EctoHosts.Overridden
  alias StatifierPersistence.Test.ReversibleBlobType
  alias StatifierPersistence.TestRepo

  describe "zero-config host (repo: only)" do
    # sabotage: Config default table_prefix changed to "statifier" -> red (sources lose the underscore)
    test "schemas read from statifier_* tables" do
      assert Default.Chart.__schema__(:source) == "statifier_charts"
      assert Default.Position.__schema__(:source) == "statifier_positions"
      assert Default.Run.__schema__(:source) == "statifier_runs"
    end

    # sabotage: primary_key/2 MFA branch returns autogenerate: false -> red (no MFA in :autogenerate)
    test "primary keys are UXID strings autogenerated with per-table prefixes" do
      for {schema, prefix} <- [
            {Default.Chart, "chart"},
            {Default.Position, "pos"},
            {Default.Run, "run"}
          ] do
        assert schema.__schema__(:type, :id) == :string

        assert {[:id], {UXID, :generate!, [[prefix: ^prefix]]}} =
                 List.keyfind(schema.__schema__(:autogenerate), [:id], 0)
      end
    end

    # sabotage: __statifier_persistence__(:repo) returns the whole config -> red
    test "exposes the resolved config and repo on the host module" do
      assert %Config{
               repo: TestRepo,
               key: {KeyGenerator.UXID, []},
               table_prefix: "statifier_",
               tables: %{},
               prefix: nil
             } = Default.__statifier_persistence__(:config)

      assert Default.__statifier_persistence__(:repo) == TestRepo
      assert Default.Chart.__schema__(:prefix) == nil
    end

    # sabotage: @fields runs list drops :failure -> red (runs field list mismatch)
    test "schemas carry the engine identity columns verbatim" do
      assert Default.Chart.__schema__(:fields) ==
               [:id, :content_hash, :identity_blob, :chart_blob, :inserted_at, :updated_at]

      assert Default.Position.__schema__(:fields) ==
               [
                 :id,
                 :session_id,
                 :content_hash,
                 :identity_blob,
                 :position_blob,
                 :inserted_at,
                 :updated_at
               ]

      assert Default.Run.__schema__(:fields) ==
               [
                 :id,
                 :run_id,
                 :status,
                 :content_hash,
                 :identity_blob,
                 :position_blob,
                 :failure,
                 :session_id,
                 :metadata,
                 :outcome_blob,
                 :inserted_at,
                 :updated_at
               ]

      # Identities are strings, blobs are binaries, verbatim per ADR-0002
      # decision 1 - never the configured key type.
      assert Default.Run.__schema__(:type, :run_id) == :string
      assert Default.Run.__schema__(:type, :content_hash) == :string
      assert Default.Run.__schema__(:type, :session_id) == :string
      assert Default.Run.__schema__(:type, :identity_blob) == :binary
      assert Default.Run.__schema__(:type, :status) == :string
      assert Default.Run.__schema__(:type, :failure) == :string
      assert Default.Position.__schema__(:type, :position_blob) == :binary
      assert Default.Chart.__schema__(:type, :chart_blob) == :binary
    end

    # sabotage: timestamps type changed to :utc_datetime -> red
    test "timestamps are utc_datetime_usec" do
      assert Default.Chart.__schema__(:type, :inserted_at) == :utc_datetime_usec
      assert Default.Chart.__schema__(:type, :updated_at) == :utc_datetime_usec
    end
  end

  describe "fully-overridden host (uuid key, prefixes, per-table override)" do
    # sabotage: Config.table/2 ignores the :tables override map -> red (runs source falls
    # back to "wf_runs")
    test "every table-name knob lands in __schema__(:source)" do
      assert Overridden.Chart.__schema__(:source) == "wf_charts"
      assert Overridden.Position.__schema__(:source) == "wf_positions"
      assert Overridden.Run.__schema__(:source) == "workflow_runs"
    end

    # sabotage: schema_ast hardcodes @schema_prefix nil -> red
    test "the Postgres schema lands in __schema__(:prefix)" do
      for schema <- [Overridden.Chart, Overridden.Position, Overridden.Run] do
        assert schema.__schema__(:prefix) == "workflows"
      end
    end

    # sabotage: Config key default resolved regardless of the :key option -> red (id type
    # comes back :string)
    test "uuid keys are Ecto.UUID fields autogenerated as UUIDv7" do
      assert Overridden.Chart.__schema__(:type, :id) == Ecto.UUID

      assert {[:id], {KeyGenerator.UUIDv7, :generate, []}} =
               List.keyfind(Overridden.Run.__schema__(:autogenerate), [:id], 0)
    end
  end

  describe "bigserial host" do
    # sabotage: primary_key/2 nil branch drops read_after_writes -> red
    test "declares database-assigned keys the repo reads back" do
      assert Bigserial.Run.__schema__(:type, :id) == :id
      assert List.keyfind(Bigserial.Run.__schema__(:autogenerate), [:id], 0) == nil
      assert Bigserial.Run.__schema__(:autogenerate_id) == nil
      assert Bigserial.Run.__schema__(:read_after_writes) == [:id]
    end
  end

  describe "blob_type option" do
    # sabotage: Config.new/1 blob_type default changed from :binary to
    # {ReversibleBlobType, []} -> red (Default's blob columns came back
    # typed ReversibleBlobType instead of :binary). Verified red,
    # reverted.
    test "defaults to :binary, unchanged from before the option existed" do
      assert %Config{blob_type: :binary} = Default.__statifier_persistence__(:config)
      assert Default.Chart.__schema__(:type, :identity_blob) == :binary
      assert Default.Chart.__schema__(:type, :chart_blob) == :binary
      assert Default.Position.__schema__(:type, :position_blob) == :binary
      assert Default.Run.__schema__(:type, :position_blob) == :binary
    end

    # sabotage: schema_ast's blob-column branch applied blob_type to
    # content_hash too -> red (content_hash's type stopped being
    # :string). Verified red, reverted.
    test "a custom blob_type reaches only the three blob columns" do
      assert %Config{blob_type: {ReversibleBlobType, []}} =
               BlobTyped.__statifier_persistence__(:config)

      assert BlobTyped.Chart.__schema__(:type, :identity_blob) == ReversibleBlobType
      assert BlobTyped.Chart.__schema__(:type, :chart_blob) == ReversibleBlobType
      assert BlobTyped.Position.__schema__(:type, :position_blob) == ReversibleBlobType
      assert BlobTyped.Run.__schema__(:type, :position_blob) == ReversibleBlobType

      assert BlobTyped.Chart.__schema__(:type, :content_hash) == :string
      assert BlobTyped.Position.__schema__(:type, :session_id) == :string
      assert BlobTyped.Run.__schema__(:type, :run_id) == :string
      assert BlobTyped.Run.__schema__(:type, :status) == :string
      assert BlobTyped.Run.__schema__(:type, :failure) == :string
    end
  end

  describe "compile-time validation" do
    # sabotage: reject_unknown! made a no-op -> red (nothing raised)
    test "an unknown option raises ArgumentError at compile time" do
      assert_raise ArgumentError, ~r/unknown option\(s\) \[:nope\]/, fn ->
        Code.compile_string("""
        defmodule StatifierPersistence.EctoTest.BadOption do
          use StatifierPersistence.Ecto, repo: Foo, nope: 1
        end
        """)
      end
    end

    # sabotage: fetch_repo! defaults a missing :repo to nil -> red (nothing raised)
    test "a missing :repo raises ArgumentError at compile time" do
      assert_raise ArgumentError, ~r/the :repo option is required/, fn ->
        Code.compile_string("""
        defmodule StatifierPersistence.EctoTest.NoRepo do
          use StatifierPersistence.Ecto, key: :uuid
        end
        """)
      end
    end

    # sabotage: validate_tables! unknown-key clause accepts any atom key -> red (nothing raised)
    test "an unknown table key raises ArgumentError at compile time" do
      assert_raise ArgumentError, ~r/unknown table key :sessions/, fn ->
        Code.compile_string("""
        defmodule StatifierPersistence.EctoTest.BadTable do
          use StatifierPersistence.Ecto, repo: Foo, tables: %{sessions: "s"}
        end
        """)
      end
    end

    # sabotage: KeyGenerator.resolve/1 catch-all returns the UXID default -> red (nothing raised)
    test "an unknown key spelling raises ArgumentError at compile time" do
      assert_raise ArgumentError, ~r/unknown key option :ulid/, fn ->
        Code.compile_string("""
        defmodule StatifierPersistence.EctoTest.BadKey do
          use StatifierPersistence.Ecto, repo: Foo, key: :ulid
        end
        """)
      end
    end

    # sabotage: ensure_blob_type_loaded! made a no-op (always :ok) -> red
    # (nothing raised for a module that cannot be loaded)
    test "a blob_type module that cannot be loaded raises ArgumentError at compile time" do
      assert_raise ArgumentError, ~r/could not be loaded/, fn ->
        Code.compile_string("""
        defmodule StatifierPersistence.EctoTest.BadBlobTypeModule do
          use StatifierPersistence.Ecto, repo: Foo, blob_type: NoSuchModuleAtAll
        end
        """)
      end
    end

    # sabotage: validate_blob_type!'s Ecto.Type/ParameterizedType check dropped, always
    # accepted -> red (nothing raised for a module that is neither)
    test "a blob_type module implementing neither Ecto.Type nor Ecto.ParameterizedType raises" do
      assert_raise ArgumentError, ~r/must implement Ecto.Type or Ecto.ParameterizedType/, fn ->
        Code.compile_string("""
        defmodule StatifierPersistence.EctoTest.BadBlobTypeBehaviour do
          use StatifierPersistence.Ecto, repo: Foo, blob_type: Enum
        end
        """)
      end
    end
  end

  describe "Config.new/1 validation not reachable through a compiling use" do
    # sabotage: validate_table_prefix! accepts any term -> red (nothing raised)
    test "rejects a non-string table_prefix" do
      assert_raise ArgumentError, ~r/:table_prefix option must be a string/, fn ->
        Config.new(repo: TestRepo, table_prefix: :statifier)
      end
    end

    # sabotage: validate_prefix! accepts any term -> red (nothing raised)
    test "rejects a non-string prefix" do
      assert_raise ArgumentError, ~r/:prefix option \(Postgres schema\) must be a string/, fn ->
        Config.new(repo: TestRepo, prefix: :workflows)
      end
    end

    # sabotage: validate_tables! map clause accepts non-string names -> red (nothing raised)
    test "rejects a non-string table override and a non-map tables option" do
      assert_raise ArgumentError, ~r/override for :runs must be a string/, fn ->
        Config.new(repo: TestRepo, tables: %{runs: :workflow_runs})
      end

      assert_raise ArgumentError, ~r/:tables option must be a map/, fn ->
        Config.new(repo: TestRepo, tables: [runs: "workflow_runs"])
      end
    end

    # sabotage: fetch_repo! accepts any term -> red (nothing raised)
    test "rejects a non-module repo and non-keyword options" do
      assert_raise ArgumentError, ~r/:repo option must be a repo module/, fn ->
        Config.new(repo: "MyApp.Repo")
      end

      assert_raise ArgumentError, ~r/expected a keyword list/, fn ->
        Config.new(%{repo: TestRepo})
      end
    end

    # sabotage: validate_blob_type!'s bare-atom clause resolved to :binary
    # unconditionally -> red (a bogus module compiled to :binary instead of
    # raising)
    test "resolves a bare module as {module, []}" do
      assert %Config{blob_type: {ReversibleBlobType, []}} =
               Config.new(repo: TestRepo, blob_type: ReversibleBlobType)
    end

    # sabotage: validate_blob_type!'s {module, opts} branch stored {module, []},
    # dropping the given opts -> red (this test caught it; the two "resolves"
    # tests above/below stayed green because they never pass opts). Verified
    # red, reverted.
    test "resolves a {module, opts} tuple, keeping the opts" do
      assert %Config{blob_type: {ReversibleBlobType, [foo: 1]}} =
               Config.new(repo: TestRepo, blob_type: {ReversibleBlobType, foo: 1})
    end

    # sabotage: validate_blob_type! second-element check used is_list/1 instead
    # of Keyword.keyword?/1 -> red (a non-keyword list like [1, 2] slipped
    # through instead of raising)
    test "rejects a {module, opts} tuple whose opts are not a keyword list" do
      assert_raise ArgumentError, ~r/second element must be a keyword list/, fn ->
        Config.new(repo: TestRepo, blob_type: {ReversibleBlobType, [1, 2]})
      end
    end

    # sabotage: validate_blob_type!'s catch-all clause made a no-op
    # (`do: other`) instead of raising -> red (nothing raised for a
    # malformed value). Verified red, reverted.
    test "rejects a malformed blob_type value" do
      assert_raise ArgumentError, ~r/:blob_type option must be :binary/, fn ->
        Config.new(repo: TestRepo, blob_type: "binary")
      end
    end
  end

  describe "the moduledoc's zero-config example" do
    # sabotage: moduledoc example switched to a `repository:` option -> red (snippet no
    # longer compiles)
    test "compiles verbatim" do
      {:docs_v1, _anno, _lang, _fmt, %{"en" => moduledoc}, _meta, _docs} =
        Code.fetch_docs(StatifierPersistence.Ecto)

      assert [example] =
               Regex.run(
                 ~r/^    defmodule MyApp\.Persistence do\n(?:    .*\n)*?    end$/m,
                 moduledoc
               ),
             "moduledoc no longer carries the zero-config example"

      code =
        example
        |> String.split("\n")
        |> Enum.map_join("\n", &String.replace_prefix(&1, "    ", ""))

      modules = code |> Code.compile_string() |> Enum.map(&elem(&1, 0))

      # Bind through variables: the modules only exist once the snippet
      # compiles, and literal remote calls would warn at test compile time.
      assert host = Enum.find(modules, &(&1 == MyApp.Persistence))
      run_schema = Module.concat(host, Run)
      assert run_schema.__schema__(:source) == "statifier_runs"
      assert host.__statifier_persistence__(:repo) == MyApp.Repo
    end
  end
end
