defmodule StatifierPersistence.Storage.EctoBlobTypeConformanceTest do
  @moduledoc """
  The lib-shipped conformance suite (ADR-0003 decision 5) run against
  `StatifierPersistence.Storage.Ecto` over the `BlobTyped` host, which
  puts `StatifierPersistence.Test.ReversibleBlobType` on `:blob_type`
  (sp-km3). Byte-identical round-tripping through a custom blob type is
  the proof the option composes with the storage contract, not just
  with the schema DSL.

  Every test here is generated by the case template, sabotage notes
  included; this module adds none of its own.
  """

  use StatifierPersistence.Testing.StorageConformance,
    async: true,
    adapter: StatifierPersistence.Storage.Ecto,
    opts: [persistence: StatifierPersistence.EctoHosts.BlobTyped, sandbox: true]
end
