defmodule StatifierPersistence.Storage.EctoConformanceTest do
  @moduledoc """
  The lib-shipped conformance suite (ADR-0003 decision 5) run against
  `StatifierPersistence.Storage.Ecto` over the zero-config Default host -
  the identical suite `InMemory` passes, against real Postgres
  (ADR-0005). Isolation comes from the adapter's own `isolate/1`
  sandbox checkout, which the suite's setup calls after `init/1`.

  Every test here is generated by the case template, sabotage notes
  included; this module adds none of its own.
  """

  use StatifierPersistence.Testing.StorageConformance,
    async: true,
    adapter: StatifierPersistence.Storage.Ecto,
    opts: [persistence: StatifierPersistence.EctoHosts.Default, sandbox: true]
end
