defmodule StatifierPersistence.Storage.InputLogConformanceTest do
  @moduledoc """
  The lib-shipped conformance suite run against
  `StatifierPersistence.Test.InputLogAdapter` - `InMemory` plus ADR-0010's
  three input-log callbacks.

  This is the opt-in arm of ADR-0010 decision 1 under test without a
  database. `StatifierPersistence.Storage.InMemory` exports none of the
  three, so `StatifierPersistence.Storage.InMemoryConformanceTest` is the
  other arm: the same suite, with the input-log cases not generated at
  all, green unchanged.

  Every test here is generated by the case template, sabotage notes
  included; this module adds none of its own.
  """

  use StatifierPersistence.Testing.StorageConformance,
    async: true,
    adapter: StatifierPersistence.Test.InputLogAdapter,
    opts: []
end
