defmodule StatifierPersistence.Storage.NoMetadataConformanceTest do
  @moduledoc """
  The lib-shipped conformance suite run against an adapter that declares no
  metadata support - `StatifierPersistence.Test.NoLockAdapter`, which
  exports neither `lock_run/3` nor `supports_metadata?/1`.

  This is the refusal arm of ADR-0006 decision 3 under test: an adapter
  that stores no metadata stays conformant by refusing a non-empty map at
  open, and the suite's metadata cases must go green on that answer exactly
  as they do on `InMemory`'s round trip. Without this module the refusal
  branch of those cases would never run in this repository's own suite.

  Every test here is generated by the case template, sabotage notes
  included; this module adds none of its own.
  """

  use StatifierPersistence.Testing.StorageConformance,
    async: true,
    adapter: StatifierPersistence.Test.NoLockAdapter,
    opts: []
end
