defmodule StatifierPersistence.Storage.NoTombstoneReadConformanceTest do
  @moduledoc """
  The lib-shipped conformance suite run against an adapter that can retire
  a chart and declares no narrow tombstone read -
  `StatifierPersistence.Test.NoTombstoneReadAdapter`.

  This is the fallback arm of the tombstone check `create/4` runs at open
  (ADR-0012 decision 6): with no `fetch_retired_info/2` to ask, the facade
  reads the whole chart row through `fetch_chart/2`, and the suite's
  facade cases must refuse a retired chart on that path exactly as they do
  on the narrow one.

  Every test here is generated by the case template, sabotage notes
  included; this module adds none of its own.
  """

  use StatifierPersistence.Testing.StorageConformance,
    async: true,
    adapter: StatifierPersistence.Test.NoTombstoneReadAdapter,
    opts: []
end
